#pragma once

#include <stdint.h>

struct EmbeddedFile
{
    const char* mName;
    const char* mData;
    uint32_t mSize;
    bool mEngine;
};

// Embedded raw-asset VFS — runtime-registration model.
//
// The generated Generated/EmbeddedAssets.cpp (when linked into a shipped exe)
// emits a static initializer that calls SYS_RegisterEmbeddedRawAssets with a
// pointer to its gEmbeddedRawAssets[] array. Editor builds don't link the
// generated cpp, so the registration never happens and lookups return null —
// no weak-symbol dance, no per-toolchain pragmas.
//
// SYS_LookupEmbeddedRawAsset matches `path` against the registered table after
// canonicalising both to forward-slashes and stripping a leading "./". Returns
// a pointer aliasing the generated byte array on hit (callers must NOT free
// it), nullptr on miss.
void SYS_RegisterEmbeddedRawAssets(EmbeddedFile* table, uint32_t count);
const char* SYS_LookupEmbeddedRawAsset(const char* path, uint32_t& outSize);
