#!/usr/bin/env python3
"""Generate minimal stub files in Standalone/Generated/ if they are missing.

Standalone/Source/Main.cpp unconditionally #includes the Generated headers
on every desktop platform (EMBEDDED_ENABLED), and Standalone.vcxproj /
Makefile_Linux_Editor reference all three Generated/*.cpp files. These
files are produced by the Editor's BuildData action (ActionManager.cpp's
GenerateEmbeddedAssetFiles) and are gitignored, so a fresh clone or CI
checkout has nothing in Standalone/Generated/ and the Standalone build
fails.

This script writes minimal, link-safe stubs only when the target file is
absent. Existing files (real assets produced by the Editor, or a previous
stub run) are left untouched.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DIR = REPO_ROOT / "Standalone" / "Generated"


EMBEDDED_ASSETS_H = """\
#include <stdint.h>
#include "EmbeddedFile.h"

extern uint32_t gNumEmbeddedAssets;
extern EmbeddedFile gEmbeddedAssets[];
extern uint32_t gNumEmbeddedRawAssets;
extern EmbeddedFile gEmbeddedRawAssets[];

extern const char gEmbeddedConfig_Data[];
extern const uint32_t gEmbeddedConfig_Size;
"""

EMBEDDED_ASSETS_CPP = """\
#include <stdint.h>
#include "EmbeddedFile.h"

uint32_t gNumEmbeddedAssets = 0;
EmbeddedFile gEmbeddedAssets[] = { {} };

uint32_t gNumEmbeddedRawAssets = 0;
EmbeddedFile gEmbeddedRawAssets[] = { {} };

void SYS_RegisterEmbeddedRawAssets(EmbeddedFile* table, uint32_t count);
namespace { struct EmbeddedRawAssetsRegistrar { EmbeddedRawAssetsRegistrar() { SYS_RegisterEmbeddedRawAssets(gEmbeddedRawAssets, gNumEmbeddedRawAssets); } }; static EmbeddedRawAssetsRegistrar sEmbeddedRawAssetsRegistrar; }

extern const char gEmbeddedConfig_Data[] = { '\\0' };
extern const uint32_t gEmbeddedConfig_Size = 0;
"""

EMBEDDED_SCRIPTS_H = """\
#include <stdint.h>
#include "EmbeddedFile.h"

extern uint32_t gNumEmbeddedScripts;
extern EmbeddedFile gEmbeddedScripts[];
"""

EMBEDDED_SCRIPTS_CPP = """\
#include <stdint.h>
#include "EmbeddedFile.h"

uint32_t gNumEmbeddedScripts = 0;
EmbeddedFile gEmbeddedScripts[] = { {} };
"""

ADDON_PLUGINS_CPP = """\
// Stub generated by Tools/generate_embedded_stubs.py.
// Real content is emitted by ActionManager::GenerateAddonPluginsRegistrar
// during a shipped (non-Editor) build.

#if !EDITOR
#endif // !EDITOR
"""


STUBS = {
    "EmbeddedAssets.h": EMBEDDED_ASSETS_H,
    "EmbeddedAssets.cpp": EMBEDDED_ASSETS_CPP,
    "EmbeddedScripts.h": EMBEDDED_SCRIPTS_H,
    "EmbeddedScripts.cpp": EMBEDDED_SCRIPTS_CPP,
    "AddonPlugins.cpp": ADDON_PLUGINS_CPP,
}


def main() -> int:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    print(f"Standalone embedded asset stubs -> {GENERATED_DIR}")

    wrote = 0
    skipped = 0
    for name, content in STUBS.items():
        target = GENERATED_DIR / name
        if target.exists():
            print(f"  [skip] {name} (exists)")
            skipped += 1
            continue
        target.write_text(content, encoding="utf-8")
        print(f"  [write] {name}")
        wrote += 1

    print(f"Done: {wrote} written, {skipped} skipped.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
