-- ~PolyphaseSharp~ generated from Door.cs - DO NOT EDIT, changes will be overwritten.
Script.Require("CSharp/CSharpCore")

-- Generated by CSharp.lua Compiler
local System = System
local Polyphase
System.import(function (out)
  Polyphase = out.Polyphase
end)
System.namespace("Game", function (namespace)
  -- Exercises the generic Script<TNode> base: Node is typed without casts.
  namespace.class("Door", function (namespace)
    local MaterialKind, HasTriangleCollision
    MaterialKind = function (this)
      local m = this.__node:GetMaterial()
      return System.is(m, Polyphase.MaterialLite) and "lite" or m:GetTypeName()
    end
    HasTriangleCollision = function (this)
      return this.__node:GetUseTriangleCollision()
    end
    return {
      base = function (out)
        return {
          out.Polyphase.Script_1(out.Polyphase.StaticMesh3D)
        }
      end,
      MaterialKind = MaterialKind,
      HasTriangleCollision = HasTriangleCollision
    }
  end)
end)

CSharpCore.Finalize({ "Game.Door" })

Door = {}

function Door:Create()
    self.openAngle = 90
    self.__cs = CSharpCore.New(Game.Door, self)
end

function Door:GatherProperties()
    return {
        { name = "openAngle", type = DatumType.Float },
    }
end

function Door:HasTriangleCollision()
    return self.__cs:HasTriangleCollision()
end

function Door:MaterialKind()
    return self.__cs:MaterialKind()
end
