-- ~PolyphaseSharp~ generated from Hud.cs - DO NOT EDIT, changes will be overwritten.
Script.Require("CSharp/CSharpCore")

-- Generated by CSharp.lua Compiler
local System = System
local Polyphase
System.import(function (out)
  Polyphase = out.Polyphase
end)
System.namespace("Game", function (namespace)
  -- Exercises: ScriptWidget bare calls, widget creation via Node.Construct, the
  -- generated static API (TimerManager / Engine), callback delegates (timer +
  -- signal), Vector2 properties, [Replicated] + OnRep, [NetFunc] + InvokeNetFunc.
  namespace.class("Hud", function (namespace)
    local Start, OnScoreChanged, S_AddScore, M_Flash, RequestScore, Tick, Elapsed, Kind, 
    Stop
    Start = function (this)
      this.label = System.as(Node.Construct("Text"), Polyphase.Text)
      this.label:SetAnchorMode(0 --[[AnchorMode.TopLeft]])
      this.label:SetPosition(this.__node.offset.x, this.__node.offset.y)
      this.label:SetText(this.__node.title)
      this.label:Attach(this.__node)

      this.mTimerId = TimerManager.SetTimer(function ()
        this.ticks = this.ticks + 1
      end, 0.5, true)

      this.__node:ConnectSignal("Scored", this.__node, function (listener, points)
        this.lastPoints = System.cast(System.Int32, points)
        this.__node.score = this.__node.score + this.lastPoints
      end)
    end
    OnScoreChanged = function (this)
      this.repCount = this.repCount + 1
    end
    S_AddScore = function (this, points)
      this.__node.score = this.__node.score + points
    end
    M_Flash = function (this)
    end
    RequestScore = function (this, points)
      this.__node:InvokeNetFunc("S_AddScore", points)
    end
    Tick = function (this, deltaTime)
      this.__node:SetOpacityFloat(1.0)
      -- bare Widget call through ScriptWidget
    end
    Elapsed = function (this)
      return Engine.GetTime()
    end
    Kind = function (this)
      return (this.__node ~= nil) and "widget" or "node"
    end
    Stop = function (this)
      TimerManager.ClearTimer(this.mTimerId)
    end
    return {
      base = function (out)
        return {
          out.Polyphase.ScriptWidget
        }
      end,
      repCount = 0,
      ticks = 0,
      lastPoints = 0,
      mTimerId = 0,
      Start = Start,
      OnScoreChanged = OnScoreChanged,
      S_AddScore = S_AddScore,
      M_Flash = M_Flash,
      RequestScore = RequestScore,
      Tick = Tick,
      Elapsed = Elapsed,
      Kind = Kind,
      Stop = Stop
    }
  end)
end)

CSharpCore.Finalize({ "Game.Hud" })

Hud = {}

function Hud:Create()
    self.offset = Vec(10, 20)
    self.score = 0
    self.title = "HUD"
    self.__cs = CSharpCore.New(Game.Hud, self)
end

function Hud:GatherProperties()
    return {
        { name = "offset", type = DatumType.Vector2D },
        { name = "title", type = DatumType.String },
    }
end

function Hud:GatherReplicatedData()
    return {
        { name = "score", type = DatumType.Integer, onRep = "OnScoreChanged" },
        { name = "title", type = DatumType.String },
    }
end

function Hud:GatherNetFuncs()
    return {
        { name = "S_AddScore", type = NetFuncType.Server, reliable = true },
        { name = "M_Flash", type = NetFuncType.Multicast, reliable = false },
    }
end

function Hud:Start()
    self.__cs:Start()
end

function Hud:Tick(deltaTime)
    self.__cs:Tick(deltaTime)
end

function Hud:Stop()
    self.__cs:Stop()
end

function Hud:Elapsed()
    return self.__cs:Elapsed()
end

function Hud:Kind()
    return self.__cs:Kind()
end

function Hud:M_Flash()
    return self.__cs:M_Flash()
end

function Hud:OnScoreChanged()
    return self.__cs:OnScoreChanged()
end

function Hud:RequestScore(points)
    return self.__cs:RequestScore(points)
end

function Hud:S_AddScore(points)
    return self.__cs:S_AddScore(points)
end
