-- ~PolyphaseSharp~ generated from LedStrip.cs - DO NOT EDIT, changes will be overwritten.
Script.Require("CSharp/CSharpCore")

-- Generated by CSharp.lua Compiler
local System = System
local Polyphase
System.import(function (out)
  Polyphase = out.Polyphase
end)
System.namespace("Game", function (namespace)
  -- Exercises engine handle types (Spline3D, StaticMesh3D, Material/MaterialLite),
  -- `as` / `is` on engine values, and [Property] arrays.
  namespace.class("LedStrip", function (namespace)
    local SetLEDs, SetSpline, SetLEDColor, GetColoredCount, SumWeights, CountMeshes, SplineLength, PointAt, 
    SelfIsStaticMesh, MaterialKind, Tick
    SetLEDs = function (this, newLEDs)
      this.__node.leds = newLEDs
    end
    SetSpline = function (this, newSpline)
      this.__node.spline = newSpline
    end
    SetLEDColor = function (this, index, color)
      if index < 0 or index >= #CSharpCore.Array(this.__node.leds, Polyphase.StaticMesh3D) then
        return false
      end

      local meshInstance = CSharpCore.Array(this.__node.leds, Polyphase.StaticMesh3D):get(index)
      if meshInstance == nil then
        return false
      end

      local material = System.as(meshInstance:GetMaterial(), Polyphase.MaterialLite)
      if material == nil then
        return false
      end

      material:SetColor(color)
      material:SetBlendMode(3 --[[BlendMode.Additive]])
      material:SetShadingModel(0 --[[ShadingModel.Unlit]])
      this.mColored = this.mColored + 1
      return true
    end
    GetColoredCount = function (this)
      return this.mColored
    end
    SumWeights = function (this)
      local sum = 0
      for _, w in System.each(CSharpCore.Array(this.__node.weights, System.Single)) do
        sum = sum + w
      end
      return sum
    end
    CountMeshes = function (this)
      local n = 0
      for i = 0, #CSharpCore.Array(this.__node.leds, Polyphase.StaticMesh3D) - 1 do
        if CSharpCore.Array(this.__node.leds, Polyphase.StaticMesh3D):get(i) ~= nil and CSharpCore.Array(this.__node.leds, Polyphase.StaticMesh3D):get(i) ~= nil then
          n = n + 1
        end
      end
      return n
    end
    SplineLength = function (this)
      return (this.__node.spline ~= nil) and this.__node.spline:GetSplineLength() or - 1
    end
    PointAt = function (this, index)
      return this.__node.spline:GetSplinePointWorldPosition((index) + 1)
    end
    SelfIsStaticMesh = function (this)
      return System.is(this.__node, Polyphase.StaticMesh3D)
    end
    MaterialKind = function (this, index)
      local m = CSharpCore.Array(this.__node.leds, Polyphase.StaticMesh3D):get(index):GetMaterial()
      if System.is(m, Polyphase.MaterialLite) then
        return "lite"
      end
      if System.is(m, Polyphase.MaterialInstance) then
        return "instance"
      end
      return m:GetTypeName()
    end
    Tick = function (this, deltaTime)
    end
    return {
      base = function (out)
        return {
          out.Polyphase.Script3D
        }
      end,
      mColored = 0,
      SetLEDs = SetLEDs,
      SetSpline = SetSpline,
      SetLEDColor = SetLEDColor,
      GetColoredCount = GetColoredCount,
      SumWeights = SumWeights,
      CountMeshes = CountMeshes,
      SplineLength = SplineLength,
      PointAt = PointAt,
      SelfIsStaticMesh = SelfIsStaticMesh,
      MaterialKind = MaterialKind,
      Tick = Tick
    }
  end)
end)

CSharpCore.Finalize({ "Game.LedStrip" })

LedStrip = {}

function LedStrip:Create()
    self.count = 160
    self.leds = self.leds or {}
    self.weights = { 1, 2, 3 }
    self.labels = { "", "" }
    self.tint = Vec(1, 0.5, 0, 1)
    self.__cs = CSharpCore.New(Game.LedStrip, self)
end

function LedStrip:GatherProperties()
    return {
        { name = "count", type = DatumType.Integer },
        { name = "spline", type = DatumType.Spline3D },
        { name = "leds", type = DatumType.Node3D, array = true },
        { name = "weights", type = DatumType.Float, array = true },
        { name = "labels", type = DatumType.String, array = true },
        { name = "tint", type = DatumType.Color },
    }
end

function LedStrip:Tick(deltaTime)
    self.__cs:Tick(deltaTime)
end

function LedStrip:CountMeshes()
    return self.__cs:CountMeshes()
end

function LedStrip:GetColoredCount()
    return self.__cs:GetColoredCount()
end

function LedStrip:MaterialKind(index)
    return self.__cs:MaterialKind(index)
end

function LedStrip:PointAt(index)
    return self.__cs:PointAt(index)
end

function LedStrip:SelfIsStaticMesh()
    return self.__cs:SelfIsStaticMesh()
end

function LedStrip:SetLEDColor(index, color)
    return self.__cs:SetLEDColor(index, color)
end

function LedStrip:SetLEDs(newLEDs)
    return self.__cs:SetLEDs(newLEDs)
end

function LedStrip:SetSpline(newSpline)
    return self.__cs:SetSpline(newSpline)
end

function LedStrip:SplineLength()
    return self.__cs:SplineLength()
end

function LedStrip:SumWeights()
    return self.__cs:SumWeights()
end
