-- ~PolyphaseSharp~ generated from Rotator.cs - DO NOT EDIT, changes will be overwritten.
Script.Require("CSharp/CSharpCore")

-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Game", function (namespace)
  namespace.class("Rotator", function (namespace)
    local Start, Tick
    Start = function (this)
      Log.Debug("Rotator started on " .. this.__node:GetName())
    end
    Tick = function (this, deltaTime)
      if not this.__node.Enabled then
        return
      end
      this.mElapsed = this.mElapsed + deltaTime
      this.__node:AddRotation((this.__node.AngularVelocity * deltaTime))
    end
    return {
      base = function (out)
        return {
          out.Polyphase.Script3D
        }
      end,
      mElapsed = 0,
      Start = Start,
      Tick = Tick
    }
  end)
end)

CSharpCore.Finalize()

Rotator = {}

function Rotator:Create()
    self.AngularVelocity = Vec(0, 90, 0)
    self.Enabled = true
    self.__cs = CSharpCore.New(Game.Rotator, self)
end

function Rotator:GatherProperties()
    return {
        { name = "AngularVelocity", type = DatumType.Vector },
        { name = "Enabled", type = DatumType.Bool, display_name = "Spin Enabled" },
    }
end

function Rotator:Start()
    self.__cs:Start()
end

function Rotator:Tick(deltaTime)
    self.__cs:Tick(deltaTime)
end
